/**
 * Minimal single-byte token table for WA binary protocol experiments.
 * This is intentionally small and does not claim full protocol coverage.
 * Tokens are public knowledge from the WhatsApp Web binary framing format.
 */

export const TAGS = {
  LIST_EMPTY: 0,
  DICTIONARY_0: 236,
  DICTIONARY_1: 237,
  DICTIONARY_2: 238,
  DICTIONARY_3: 239,
  INTEROP_JID: 245,
  FB_JID: 246,
  AD_JID: 247,
  LIST_8: 248,
  LIST_16: 249,
  JID_PAIR: 250,
  HEX_8: 251,
  BINARY_8: 252,
  BINARY_20: 253,
  BINARY_32: 254,
  NIBBLE_8: 255,
  SINGLE_BYTE_MAX: 256,
  PACKED_MAX: 254,
} as const;

/** Common single-byte string tokens (subset). Index = token id. */
export const SINGLE_BYTE_TOKENS = [
  "",
  "xmlstreamstart",
  "xmlstreamend",
  "s.whatsapp.net",
  "type",
  "participant",
  "from",
  "receipt",
  "id",
  "notification",
  "disappearing_mode",
  "status",
  "jid",
  "offline",
  "message",
  "ack",
  "class",
  "xmlns",
  "presence",
  "to",
  "iq",
  "t",
  "encrypt",
  "action",
  "attributes",
  "stream:error",
  "code",
  "success",
  "failure",
  "result",
  "value",
  "key",
  "media",
  "count",
  "devices",
  "device",
  "name",
  "picture",
  "chat",
  "group",
  "subject",
  "creation",
  "description",
  "participants",
  "member",
  "admin",
  "text",
  "body",
  "item",
  "set",
  "get",
  "query",
  "list",
  "user",
  "contact",
  "contacts",
  "presence",
  "unavailable",
  "available",
  "composing",
  "recording",
  "paused",
  "image",
  "video",
  "audio",
  "document",
  "sticker",
  "url",
  "size",
  "mimetype",
  "filehash",
  "enc",
  "iv",
  "mediaKey",
  "direct_path",
  "mediaKeyTimestamp",
  "fileLength",
  "width",
  "height",
  "seconds",
  "ptt",
  "caption",
  "contextInfo",
  "stanzaId",
  "participant",
  "quotedMessage",
  "remoteJid",
  "fromMe",
  "ephemeral",
  "expiration",
  "conversation",
  "extendedTextMessage",
  "imageMessage",
  "videoMessage",
  "audioMessage",
  "documentMessage",
  "stickerMessage",
  "protocolMessage",
  "senderKeyDistributionMessage",
  "buttonsMessage",
  "templateMessage",
  "listMessage",
  "reactionMessage",
  "encVersion",
  "deviceList",
  "device-list",
  "verifiedName",
  "verifiedLevel",
  "biz",
  "verified_name",
  "notify",
  "call",
  "offer",
  "accept",
  "reject",
  "relaylatency",
  "te2",
  "te",
  "retry",
  "registration",
  "type",
  "reason",
  "offline",
  "props",
  "config",
  "version",
  "platform",
  "os",
  "browser",
  "web",
  "desktop",
  "android",
  "ios",
  "passive",
  "read",
  "played",
  "error",
  "phone",
  "lid",
  "username",
  "server",
  "device_index",
  "agent",
  "device_id",
] as const;

export type SingleByteToken = (typeof SINGLE_BYTE_TOKENS)[number];
