/**
 * Terminal QR helpers.
 *
 * Real WhatsApp QR payloads are produced only after a successful Noise handshake
 * and client-hello exchange. Until that layer is implemented, no scannable QR
 * is generated by the library.
 */

export function printQRInTerminal(qr: string): void {
  console.log("[KaguneX] QR payload:");
  console.log(qr);
}

export function formatQRForDisplay(qr: string): string {
  return qr;
}
